package homework.enums;

/**
 * Created by Mikhail on 04.06.2018
 */
public enum MainHeader {

    MAIN_CONTENT_TITLE("EPAM FRAMEWORK WISHES…"),
    MAIN_CONTENT_TEXT("LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISICING ELIT, SED DO EIUSMOD TEMPOR" +
            " INCIDIDUNT UT LABORE ET DOLORE MAGNA ALIQUA. UT ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCITATION" +
            " ULLAMCO LABORIS NISI UT ALIQUIP EX EA COMMODO CONSEQUAT DUIS AUTE IRURE DOLOR IN REPREHENDERIT" +
            " IN VOLUPTATE VELIT ESSE CILLUM DOLORE EU FUGIAT NULLA PARIATUR.");

    public String text;

    MainHeader(String text) {
        this.text = text;
    }
}
